"""empty message

Revision ID: 7cfda443a380
Revises: a6bfa18bb95e
Create Date: 2025-04-10 21:24:50.262946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cfda443a380'
down_revision = 'a6bfa18bb95e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_confirm')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_confirm', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
